@startuml Stage Transition
!theme blueprint


[*] --> Opening

Opening --> GaolStage : Press Any Key
note on link
  スキップ可能なムービーを流す
end note
GaolStage --> LabStage : 研究施設内へ続く梯子に到達
LabStage --> UndergroundStage : 正体不明の何かに襲われる
UndergroundStage --> BossStage : 出口に続くはずだった行き止まりに到達
BossStage -l> EndGame : ボスから逃げ切る
note on link
  無事に研究施設の外に辿り着き
  陽の光に目を細める
end note
EndGame -u-> Opening
Opening -> [*] : Quit Game

Opening : ゲーム起動時のスタート画面

GaolStage : [チュートリアル]
GaolStage : 基本操作を覚えながら地上を目指す

LabStage : [謎解き]
LabStage : 何十にも掛けられたセキュリティを解きながら
LabStage : 研究施設脱出の糸口を探す

UndergroundStage : [ステルス]
UndergroundStage : 何者かの影から逃げながら出口を目指す

BossStage : 迫りくる脅威を振り払って駆け抜ける

note right of EndGame
  クレジットを流す
end note

@enduml